### ISSUE TITLE
App_openSIM pattern generator

### ISSUE THREAD

**Issue by ranranking** [bionanoimaging/UC2-GIT#37]
The pattern generation plugin from fairSIM is not on their github anymore or i didnt find the right path to find it.
pattern-generation software

**Comment by beniroquai** [comment]
Thanks for reaching out. 

There is a matlab-based version which you can find here:
[https://github.com/nanoimaging/fastSIM_GratingSearchforSLM](https://github.com/nanoimaging/fastSIM_GratingSearchforSLM). 

I'll add this to the README! Thanks for the comment.

**Comment by beniroquai** [comment]
Also the SLM Grating generator can be found here:
[SLM_GratingSearch.jar](https://github.com/fairSIM/fastSIM-GratingSearch/releases)
