### ISSUE TITLE
Allow to mount 50mm diameter lenses

### ISSUE THREAD

**Issue by RainerHeintzmann** [bionanoimaging/UC2-GIT#41]
Many of the easily available lenses (e.g. form Ajax Scientific have 50 mm diameter. It would be useful to also be able to mount them. 
They just about fit in the standard cube, but a different mount would be needed. It is not so important to have to full size as a transmitting surface.
Can one make a design for a variable holder for big lenses?

In addition it may also be interesting to make a design for a holder that can even deal with 10 cm lenses at a large distance from the front cube, for example to build a telescope with a 10cm entrance lense.

**Comment by beniroquai** [comment]
Sounds interesting. We could definitely make a lens holder for the big lenses.

Something like this:
![image](https://user-images.githubusercontent.com/4345528/90176020-a45ca280-dda8-11ea-9742-bcdd8399f495.png)

Can you please add more information about the lens diameter and thickness? 
A generic 50mm lens holder can be found here:
[20_Lens_holder_DIA_50mm.stl.zip](https://github.com/bionanoimaging/UC2-GIT/files/5070951/20_Lens_holder_DIA_50mm.stl.zip)

Would you mind to provide a drawing for the in-front-of-the-lens idea? That would help to clarify it a bit.

**Comment by RainerHeintzmann** [comment]
That's pretty good. A retainment ring, which has the same size as your aperture and is flat and squishy would be good.

**Comment by beniroquai** [comment]
Certainly. Would you mind to print this and see if this works? If so, I'll
provide the retain ring. We need to come up with an adjusted design though.
What are the lenses thicknesses?

Am Fr., 14. Aug. 2020 um 14:40 Uhr schrieb RainerHeintzmann <
notifications@github.com>:

**Comment by RainerHeintzmann** [comment]
Here are the approximate measures:
(Double convex),  diameter= 50 mm, d_center=4,9mm, d_side=1.9mm
(Double concave), dameter=49,0mm, d_center=, d_side=4,8mm
(Convex-Concave, diameter=48,6mm, d_center=3.1m
( Concave -Convex), diameter=48,4mm, d_center=3,8mm
(Plano-concave), diameter=49,2mm, d_center=4,5mm
(Plano-convex), diameter=49,1mm, d_center=4,7, d_side=2,3mm

**Comment by beniroquai** [comment]
Please find the new version of the lens adapter here:
[20_Lens_holder_DIA_50mm.zip](https://github.com/bionanoimaging/UC2-GIT/files/5120546/20_Lens_holder_DIA_50mm.zip)

If printed correctly it looks like this:
![image](https://user-images.githubusercontent.com/4345528/91103461-d1903700-e66b-11ea-81ab-cc243c90610d.png)

@b286 do you think one can add this design to the Thingiverser?

**Comment by b286** [comment]
Making it adaptable to the lens thickness? That shouldn't be difficult, I'll make the openSCAD design for it.
