### ISSUE TITLE
Add DOI badge to the github

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/UC2-GIT#44]
In case someone wants to cite this repo we need a DOI badge from our Zenodo archive or the biorxiv preprint. 

@b286 would you mind to take care of that?

**Comment by b286** [comment]
Like this for the biorxiv preprint: 
[![DOI:10.1101/2020.03.02.973073](http://img.shields.io/badge/DOI-10.1101/2020.03.02.973073-B31B1B.svg)](https://doi.org/10.1101/2020.03.02.973073) 

To get a DOI badge for the repository from Zenodo is a bit more difficult. We'd need to create a release and they kind of do not consider that someone wants to do this for anything else than software.

**Comment by beniroquai** [comment]
<3!! 
Let's DOIt!

**Comment by b286** [comment]
When you share the links to the badges that Zenodo created for our GITs, I'll add them all to the readme

**Comment by beniroquai** [comment]
So the actual DOI has changed. It's this now:
```10.5281/zenodo.4018965``` 

Available here
[https://zenodo.org/badge/doi/10.5281/zenodo.4018965.svg](https://zenodo.org/badge/doi/10.5281/zenodo.4018965.svg)
![https://zenodo.org/badge/doi/10.5281/zenodo.4018965.svg](https://zenodo.org/badge/doi/10.5281/zenodo.4018965.svg)

**Comment by b286** [comment]
Will you please also provide the DOI links? I've tried to search for it but it claims this doesn't exist.

**Comment by beniroquai** [comment]
Would you also mind to add these two for the Hardware git:
[![DOI](https://zenodo.org/badge/145216636.svg)](https://zenodo.org/badge/latestdoi/145216636)

and the Software git:
[![DOI](https://zenodo.org/badge/199883118.svg)](https://zenodo.org/badge/latestdoi/199883118)

to places where you intended to have them? 

Thank you! :-) 
Now the code becomes citable

The DOI from zenodo becomes active once we publish it.

**Comment by franciscozorrilla** [comment]
Hi I was wondering if you could share how you created the red bioarxiv DOI badge? Would love to make one for my preprint :)

**Comment by b286** [comment]
Hi, 

I used the generic badge for GitHub as described [here](https://academia.stackexchange.com/questions/27341/flair-badge-for-arxiv-paper), in particular:

`[![DOI:<your number>](http://img.shields.io/badge/DOI-<your number>-<colour hexcode>.svg)](<doi link>)`

Using a colour that is somewhat specific for the journal or preprint service. B31B1B for bioarxiv. 

So for our preprint in bioarxiv `[![DOI:10.1101/2021.01.08.425840](http://img.shields.io/badge/DOI-10.1101/2021.01.08.425840-B31B1B.svg)](https://doi.org/10.1101/2021.01.08.425840)` yields [![DOI:10.1101/2021.01.08.425840](http://img.shields.io/badge/DOI-10.1101/2021.01.08.425840-B31B1B.svg)](https://doi.org/10.1101/2021.01.08.425840)
