### ISSUE TITLE
Smartphone holder v3

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/UC2-GIT#47]
Do we want to have the smartphone holder slidable, or would it be even better to stack them to the pins of the new cubes like the plate for the LED I showed you recently? 
@b286

**Comment by b286** [comment]
Curent v3 version is slidable, placed inside the cube before closing it. 

I find it a more stable solution than printed holes for the pins, since the plate is supposed to carry the weight of a phone. For LEDs it's not an issue, given that they don't weigh almost anything.
