### ISSUE TITLE
"Inner Cube" For parts which lack enough supporting material

### ISSUE THREAD

**Issue by beniroquai** [bionanoimaging/UC2-GIT#51]
For parts like the AlliedVision camera, we should perhaps design inserts that are an inner cube rather than just a plate. This could help the part to not move around. 
What do you think @b286 ?

**Comment by b286** [comment]
This would definitely improve the stability but also limit the alignment range. Personally I didn't have any trouble with the camera moving around but I did have to align it to a certain position. 

It would also increase the printing time of those inserts. 

We ca design something like this and try it out :)

**Comment by beniroquai** [comment]
Hmh. The camera is not really stably mounted inside the cube. Perhaps this is better:
![image](https://user-images.githubusercontent.com/4345528/103918626-5194d600-510f-11eb-94c7-6a30065c8760.png)

What do you think?
@ranranking

**Comment by ranranking** [comment]
Can we maybe not use two walls here? Is it not good for cooling? I dont know if it will be better, have kind of inner post from the bottom of the camera plate to the 'roof', which direct contact with the four vertical pillar of the cube, and fix the plate.
Or just make the wall on top side as well and have a opening window, which can fix a 12v fan inside ^^

**Comment by beniroquai** [comment]
Would you mind making a sketch or even a CAD drawing? ;)

**Comment by beniroquai** [comment]
@ranranking made this:
![image](https://user-images.githubusercontent.com/4345528/104088868-1c50cb00-526a-11eb-9d3b-233c2545ee3c.png)

It works very well. We should upgrade at least the camera insert with this. 
Can you please do that @ranranking ? replace the original version with yours and close this issue? Thanks!

**Comment by ranranking** [comment]
I have saved the new version with camera in V3 folder with the name of Assembly_Cube_AlliedVision_Alvium_v3

**Comment by beniroquai** [comment]
Cool! Thanks a lot :)

Am Mo., 11. Jan. 2021 um 10:58 Uhr schrieb ranranking <
notifications@github.com>:
